### ISSUE TITLE
Allow managing multiple user profiles

### ISSUE THREAD

**Issue by johnafogarty4** [lostintangent/gistpad#139] opened 2020-03-29 12:32 UTC
It would be helpful for those of us with multiple GIT accounts if there was a simple way to swap between them.

**Comment by lostintangent** [comment] 2020-03-29 14:40
Hey! So you’d like to log into GitHub with multiple different tokens, and have a simple way to label them (e.g. work vs personal) and switch between them? That makes total sense, I just wanted to ensure I understand what you were thinking 👍

**Comment by johnafogarty4** [comment] 2020-03-29 15:20
That is exactly what I am looking for.  Thank you for understanding.

**Comment by Akv2021** [comment] 2020-11-21 19:31
Hi, Here is an example of the implementation
https://github.com/kenhowardpdx/vscode-gist#github-profiles

**Comment by lostintangent** [comment] 2023-12-10 01:55
I'm going close this as a duplicate of #96, since the core gap in GistPad is the ability to support GHE. And since VS Code is managing the user authentication sessions, I'd want to rely on them for supporting profiles, as opposed to trying to implement it myself.

**Closed by lostintangent** 2023-12-10 01:55 UTC
Labels: enhancement, area: auth, area: github

**Comment by M3R14M** [comment] 2024-06-21 11:22
How about those of us that have 2 separate, non-Enterprise accounts (1 free, 1 pro)? I can't get myself to log out of GistPad at all, revoking access doesn't work either and on sign-in it doesn't allow me to pick one of the GitHub accounts attached to VS Code auth, it just defaults to the first one I used. 

Looking at 55b4f21, it used to have GitHub OAuth. Is it perhaps possible to add this back as an option next to VS Code auth? This would theoretically enable the option to add multiple different users.
