### ISSUE TITLE
[Enterprise] Can't use token with enterprise GitHub server

### ISSUE THREAD

**Issue by GuyKh** [lostintangent/gistpad#205] opened 2021-01-13 13:56 UTC
**Describe the bug**
I've overridden the apiUrl
`    "gistpad.apiUrl": "https://mygitserver.com/api/v3",`
But when trying to signin (either by the command pallette or through the button on the top left)
![image](https://user-images.githubusercontent.com/3136012/104459496-7a0c4c80-55b5-11eb-9f45-45c975dae39f.png)

**To Reproduce**
1. Go to Settings.
2. Search for Gisthub
3. Modify **Gistpad: Api URL** and save
4. Click on Command+Shift+P and select Gistpad: Sign In...

**Expected behavior**
Since I'm overriding the apiUrl - no need to take me to 
**https://vscode-auth.github.com/authorize/?callbackUri=vscode://vscode.github-authentication/did-authenticate%253FwindowId%253D1&scope=gist%20repo&state=[unique-id]&responseType=code&authServer=https://github.com**
and instead skip this step and just expect a Github token.

**Screenshots**

**Desktop (please complete the following information):**
 - VS Code Version [v1.52.1]
 - GistPad Version [v0.2.1]

**Additional context**

**Comment by lostintangent** [comment] 2022-04-16 19:14
Closing this as a duplicate of #96.

**Closed by lostintangent** 2022-04-16 19:14 UTC
Labels: bug
