### ISSUE TITLE
Enable Use of Organizations in gistpad which we own in github

### ISSUE THREAD

**Issue by CoderTeam1** [lostintangent/gistpad#220] opened 2021-04-13 10:36 UTC
**Is your feature request related to a problem? Please describe.**
# A clear and concise description of what the problem is. Ex. I'm always frustrated when [I want to Access my organization in Gistpad but cant get it]

**Describe the solution you'd like**
# Like you have given the ability to access user accounts in github please give the ability to access organozations that we own or are a member of.

**Comment by lostintangent** [comment] 2021-09-06 02:36
Closing this as a duplicate of #96

**Closed by lostintangent** 2021-09-06 02:36 UTC
Labels: enhancement
