### ISSUE TITLE
Show link when creating a gist

### ISSUE THREAD

**Issue by maicol07** [lostintangent/gistpad#249] opened 2021-09-29 09:34 UTC
**Is your feature request related to a problem? Please describe.**
When I create a gist I have to go to my github profile to find its link

**Describe the solution you'd like**
I would like a notification when the gist has been created/uplaoded with the link and a button to copy it

**Describe alternatives you've considered**
None

**Comment by lostintangent** [comment] 2021-11-20 21:35
Hey! If you right-click the gist in the `Gists` tree, you can click the `Copy GitHub URL` menu in order to get its URL. Would that be sufficient? GistPad has a pretty sizeable user base at this point, and so it would be pretty disruptive to introduce a new toast like this, after creating a new gist. So if we added it, it would need to be disabled by default.

![image](https://user-images.githubusercontent.com/116461/142741516-cfbefef1-b0b9-49bf-bbc3-d16092d6ff95.png)

**Comment by lostintangent** [comment] 2022-04-15 16:05
Closing this issue as "by design" per the previous comment. If folks would like us to re-consider this UX, please re-open the issue and we can discuss it. Thanks!

**Closed by lostintangent** 2022-04-15 16:05 UTC
Labels: enhancement
