### ISSUE TITLE
Any possible to search gists by some key words?

### ISSUE THREAD

**Issue by x2x4com** [lostintangent/gistpad#336] opened 2023-09-08 12:28 UTC
Some kind of search function, easy search i need by key words in mass gists

**Comment by runwinged** [comment] 2023-09-10 00:46
That will be awesome, like Command + P for searching files in workspace.

**Comment by lostintangent** [comment] 2023-12-10 01:16
Hey! This is a duplicate of #48, so I'm going to close it, and centralize the conversation in that issue. Thanks!

**Closed by lostintangent** 2023-12-10 01:16 UTC
Labels: enhancement
