### ISSUE TITLE
Update gist in GitHub when user press a keybind / save

### ISSUE THREAD

**Issue by AxoCode** [lostintangent/gistpad#224] opened 2021-05-17 14:52 UTC
**Is your feature request related to a problem? Please describe.**
So I realize when I use an autosave (afterDelay), its keep updating to Github. Sending request every second (depends on your delay). And then, I realize I hit the rate limit of the gistpad API. And I can't update anymore at that time.

**Describe the solution you'd like**
So like vscode formatter, Maybe just update it when the user **actually** save it (like ctrl s) or add a command, and attach a keybind for it (just like format document) instead of check if it saves or not

**Comment by lostintangent** [comment] 2022-04-15 16:06
Closing this as a duplicate of #276. We'll introduce a seperate save behavior from VS Code, to provide the user with more control. Thanks!

**Closed by lostintangent** 2022-04-15 16:06 UTC
Labels: enhancement
